# Selcting Data

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("LaptopData.csv")

In [12]:
df.head(10)

,Brand,Model,Processor,RAM_GB,Storage_GB,Screen_Size_inch,Graphics,Price_USD
0,HP,ZenBook,AMD Ryzen 5,8,512,17.3,NVIDIA MX350,1099
1,Dell,ZenBook,AMD Ryzen 3,32,256,13.3,AMD Radeon,972
2,Asus,Gram,Apple M1,32,128,13.3,NVIDIA MX350,1129
3,Apple,Gram,Intel i3,4,512,11.6,Integrated,1304
4,Apple,Galaxy,Apple M2,8,256,15.6,NVIDIA MX350,953
5,Lenovo,ThinkPad,AMD Ryzen 5,32,128,15.6,NVIDIA GTX 1650,953
6,HP,Galaxy,AMD Ryzen 5,4,512,17.3,NVIDIA GTX 1650,1315
7,Toshiba,Satellite,Apple M2,4,1024,17.3,AMD Radeon,1153
8,HP,Galaxy,AMD Ryzen 3,16,128,17.3,Integrated,906
9,LG,Aspire,Apple M1,16,256,11.6,AMD Radeon,1108

## Selecting Data by loc() and iloc()
#### loc() is label-based, so we have to specify rows and columns based on their index/row and column labels

#### iloc() is integer position-based, so we have to specify rows and columns by their integer position values(0-based integer position)

In [13]:
# set index 
df.set_index("Brand")

,Model,Processor,RAM_GB,Storage_GB,Screen_Size_inch,Graphics,Price_USD
Brand,,,,,,,
HP,ZenBook,AMD Ryzen 5,8,512,17.3,NVIDIA MX350,1099
Dell,ZenBook,AMD Ryzen 3,32,256,13.3,AMD Radeon,972
Asus,Gram,Apple M1,32,128,13.3,NVIDIA MX350,1129
Apple,Gram,Intel i3,4,512,11.6,Integrated,1304
Apple,Galaxy,Apple M2,8,256,15.6,NVIDIA MX350,953
...,...,...,...,...,...,...,...
LG,Inspiron,Apple M1,32,128,11.6,NVIDIA GTX 1650,992
Lenovo,ZenBook,AMD Ryzen 7,32,512,11.6,NVIDIA GTX 1650,1312
Toshiba,Aspire,Intel i3,16,1024,14.0,NVIDIA GTX 1650,1048
Dell,ZenBook,Intel i5,8,256,13.3,Integrated,1209.03
Toshiba,Gram,Apple M1,4,128,11.6,AMD Radeon,809.39

In [14]:
df.set_index("Graphics", inplace=True)

In [15]:
df

,Brand,Model,Processor,RAM_GB,Storage_GB,Screen_Size_inch,Price_USD
Graphics,,,,,,,
NVIDIA MX350,HP,ZenBook,AMD Ryzen 5,8,512,17.3,1099
AMD Radeon,Dell,ZenBook,AMD Ryzen 3,32,256,13.3,972
NVIDIA MX350,Asus,Gram,Apple M1,32,128,13.3,1129
Integrated,Apple,Gram,Intel i3,4,512,11.6,1304
NVIDIA MX350,Apple,Galaxy,Apple M2,8,256,15.6,953
...,...,...,...,...,...,...,...
NVIDIA GTX 1650,LG,Inspiron,Apple M1,32,128,11.6,992
NVIDIA GTX 1650,Lenovo,ZenBook,AMD Ryzen 7,32,512,11.6,1312
NVIDIA GTX 1650,Toshiba,Aspire,Intel i3,16,1024,14.0,1048
Integrated,Dell,ZenBook,Intel i5,8,256,13.3,1209.03
AMD Radeon,Toshiba,Gram,Apple M1,4,128,11.6,809.39

In [8]:
df

In [16]:
# Select columns
df[["Model", "Processor", "RAM_GB",	"Storage_GB", "Screen_Size_inch", "Price_USD"]]

,Model,Processor,RAM_GB,Storage_GB,Screen_Size_inch,Price_USD
Graphics,,,,,,
NVIDIA MX350,ZenBook,AMD Ryzen 5,8,512,17.3,1099
AMD Radeon,ZenBook,AMD Ryzen 3,32,256,13.3,972
NVIDIA MX350,Gram,Apple M1,32,128,13.3,1129
Integrated,Gram,Intel i3,4,512,11.6,1304
NVIDIA MX350,Galaxy,Apple M2,8,256,15.6,953
...,...,...,...,...,...,...
NVIDIA GTX 1650,Inspiron,Apple M1,32,128,11.6,992
NVIDIA GTX 1650,ZenBook,AMD Ryzen 7,32,512,11.6,1312
NVIDIA GTX 1650,Aspire,Intel i3,16,1024,14.0,1048
Integrated,ZenBook,Intel i5,8,256,13.3,1209.03
AMD Radeon,Gram,Apple M1,4,128,11.6,809.39

In [17]:
df[["Model", "Processor", "Storage_GB",  "Price_USD"]]

                    Model    Processor Storage_GB Price_USD
Graphics
NVIDIA MX350      ZenBook  AMD Ryzen 5        512      1099
AMD Radeon        ZenBook  AMD Ryzen 3        256       972
NVIDIA MX350         Gram     Apple M1        128      1129
Integrated           Gram     Intel i3        512      1304
NVIDIA MX350       Galaxy     Apple M2        256       953
...                   ...          ...        ...       ...
NVIDIA GTX 1650  Inspiron     Apple M1        128       992
NVIDIA GTX 1650   ZenBook  AMD Ryzen 7        512      1312
NVIDIA GTX 1650    Aspire     Intel i3       1024      1048
Integrated        ZenBook     Intel i5        256   1209.03
AMD Radeon           Gram     Apple M1        128    809.39

[168 rows x 4 columns]

In [18]:
df=df[["Model", "Processor", "Storage_GB",  "Price_USD"]]

In [19]:
df

                    Model    Processor Storage_GB Price_USD
Graphics
NVIDIA MX350      ZenBook  AMD Ryzen 5        512      1099
AMD Radeon        ZenBook  AMD Ryzen 3        256       972
NVIDIA MX350         Gram     Apple M1        128      1129
Integrated           Gram     Intel i3        512      1304
NVIDIA MX350       Galaxy     Apple M2        256       953
...                   ...          ...        ...       ...
NVIDIA GTX 1650  Inspiron     Apple M1        128       992
NVIDIA GTX 1650   ZenBook  AMD Ryzen 7        512      1312
NVIDIA GTX 1650    Aspire     Intel i3       1024      1048
Integrated        ZenBook     Intel i5        256   1209.03
AMD Radeon           Gram     Apple M1        128    809.39

[168 rows x 4 columns]