In [1]:
import pandas as pd
df = pd.read_csv('InternationalCricketor.csv')
df.head(10)

,Player Name,Country,Matches,Innings,Runs,Average,Strike Rate,Wickets,Bowling Average,Economy
0,Virat Kohli,India,302,289,13906,58.07,93.58,4,72.25,5.23
1,Rohit Sharma,India,262,256,10709,48.96,91.72,8,56.38,5.78
2,Babar Azam,Pakistan,120,120,5084,56.81,89.12,1,120.00,6.00
3,Steve Smith,Australia,195,182,9449,46.82,82.34,0,0.00,0.00
4,Joe Root,England,171,167,7479,47.62,89.36,1,69.00,5.69
5,Kane Williamson,New Zealand,167,162,6894,47.15,80.65,1,30.00,4.50
6,AB de Villiers,South Africa,228,218,10014,53.50,101.09,3,46.67,5.33
7,David Warner,Australia,169,168,7074,45.28,95.45,0,0.00,0.00
8,Quinton de Kock,South Africa,155,152,6446,40.31,95.45,0,0.00,0.00
9,Ross Taylor,New Zealand,233,215,8184,45.69,83.25,3,52.00,5.20

In [5]:
# set Index
df.set_index("Player Name", inplace=True)

##  1 Selecting With a single value
##### loc[row_label, column_label]

In [6]:
# get all data about Rohit Sharma 
df.loc['Babar Azam']

Country            Pakistan
Matches                 120
Innings                 120
Runs                   5084
Average               56.81
Strike Rate           89.12
Wickets                   1
Bowling Average       120.0
Economy                 6.0
Name: Babar Azam, dtype: object

In [9]:
# get the run
df.loc['Babar Azam',"Runs"]

np.int64(5084)